### ISSUE TITLE
[Client] Create unit system (Classes, Display and Selection)

### ISSUE THREAD

**Issue by GeoYS** [GeoYS/game1#4]
Make an AoE like system 

- [x] Testing button to spawn units
- [ ] Unit attributes:
    - Health bar
    - Ranged/Melee 
    - Stats: Max Health, Damage
    - Status Effects: Buffs, Debuffs, Other
    - Skills/Actions applicable for unit
- [ ] Left Mouse rectangle to select units or click to select individual unit
    - States for what is selected: NPC_ONLY, NPC_AND_STRUCTURES, STRUCTURES_ONLY, single vs. multi
    - Highlight selected units (miniature rectangles?) 
 - [ ] Click away to deselect

**Comment by martinlai** [comment]
Clarification - I remember you mentioned it would be kind of like a moba game with a single hero for each player? This task is still relevant in that case, but depending on if we want an AoE-like unit system or a single-hero unit system that could make the implementation different.

**Comment by GeoYS** [comment]
The initial idea was that a player can only control, as far as movement and enemy targeting, a single hero unit. The player is still able to select other non-hero units to see their stats and perhaps activate skills they might have.

**Comment by martinlai** [comment]
Split environment interaction part of unit system to Issue #22
